[tool.black]
line-length = 79
target-version = ['py36']
preview = true
[tool.pylint.main]
disable = ["invalid-name", "import-error", "logging-fstring-interpolation", "unused-argument", "broad-except"]
[tool.pylint.format]
max-line-length = 79
[tool.pylint.TYPECHECK]
generated-members = "sh"
[tool.pylint.DESIGN]
max-attributes = 10
