[tool.black]
line-length = 79
target-version = ['py36']
preview = true
[tool.pylint.main]
disable = ["invalid-name", "import-error", "logging-fstring-interpolation", "unused-argument"]
[tool.pylint.format]
max-line-length = 79
